F66 (#80)
* initial

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* added path

* changes

* test

* final push

* final push

* recent changes

* test

* tested assignent 7

* removed redundant files

* removed ds store

* final chanegs

* recent changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* changes to workflow

* changes

* debug msgs

* debug msgs

* final changes

* final changes

* final changes

* final changes

diff --git a/.github/workflows/packer-build.yaml b/.github/workflows/packer-build.yaml
--- a/.github/workflows/packer-build.yaml
+++ b/.github/workflows/packer-build.yaml
@@ -111,6 +111,9 @@ jobs:
             if [ "$STATUS" == "Successful" ]; then
               echo "Instance refresh for Launch Template ID in Auto Scaling Group completed successfully."
               break
+            elif [ "$STATUS" == "Cancelled" ]; then
+              echo "Instance refresh for Launch Template ID in Auto Scaling Group failed."
+              exit 1
             elif [ "$STATUS" == "Failed" ]; then
               echo "Instance refresh for Launch Template ID in Auto Scaling Group failed."
               exit 1
