F63 (#77)
* initial

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* added path

* changes

* test

* final push

* final push

* recent changes

* test

* tested assignent 7

* removed redundant files

* removed ds store

* final chanegs

* recent changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* workflow changes

* changes to workflow

* changes

* debug msgs

* debug msgs

* final changes

diff --git a/.github/workflows/packer-build.yaml b/.github/workflows/packer-build.yaml
--- a/.github/workflows/packer-build.yaml
+++ b/.github/workflows/packer-build.yaml
@@ -104,6 +104,33 @@ jobs:
           aws autoscaling start-instance-refresh --auto-scaling-group-name $AUTO_SCALING_GROUP_NAME
           echo "Instance refresh for Launch template in ASG completed"      
       
+
+      - name: Instance refresh auto scale to use new launch template version
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEMO_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEMO_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          AUTO_SCALING_GROUP_NAME: ${{ secrets.AUTO_SCALING_GROUP_NAME }}
+        run: |
+          INSTANCE_REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name $AUTO_SCALING_GROUP_NAME --query 'InstanceRefreshId' --output text)
+          echo "Instance refresh for Launch template ID in AS started with ID: ${INSTANCE_REFRESH_ID}"
+
+          # Wait for the instance refresh to complete
+          while true; do
+            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name auto-scaling-group --instance-refresh-ids ${INSTANCE_REFRESH_ID} --query 'InstanceRefreshes[0].Status' --output text)
+            if [ "$STATUS" == "Successful" ]; then
+              echo "Instance refresh for Launch template ID in AS completed successfully."
+              break
+            elif [ "$STATUS" == "Failed" ]; then
+              echo "Instance refresh for Launch template ID in AS failed."
+              exit 1
+            else
+              echo "Waiting for instance refresh to complete. Current status: $STATUS"
+              sleep 60  # Adjust the sleep interval as needed
+            fi
+          done
+
+
       - name: Check Previous Step Status
         run: exit 1
         if: ${{ failure() }}
